version: '3.8'

services:
  app:
    container_name: meu-container-app
    build:
      context: .
      dockerfile: Dockerfile
      image: senai-jcmsilv-conuv-php:0.0.1
    volumes:
      - ./meu_app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./source.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    env_file:
      - ./source.env

volumes:
  mysql_data:
